-- Ascio TMCH (Trademark Clearinghouse) module database schema

CREATE TABLE IF NOT EXISTS `mod_ascio_tmch` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `order_id` VARCHAR(50) NOT NULL,
    `whmcs_service_id` INT(11) NOT NULL,
    `user_id` INT(11) NOT NULL,
    `handle` VARCHAR(50) NULL,
    `mark_name` VARCHAR(255) NOT NULL COMMENT 'Trademark name',
    `mark_id` VARCHAR(100) NULL COMMENT 'TMCH Mark ID',
    `mark_type` VARCHAR(50) NOT NULL DEFAULT 'Trademark' COMMENT 'Trademark, TreatyOrStatute, CourtValidated',
    `service_type` VARCHAR(50) NOT NULL DEFAULT 'Sunrise' COMMENT 'Sunrise, Claims',
    `goods_and_services` TEXT NULL COMMENT 'Description of goods and services',
    `labels` TEXT NULL COMMENT 'JSON array of domain labels',
    `notification_frequency` VARCHAR(50) NULL DEFAULT 'Daily',
    `claim_email_1` VARCHAR(255) NULL,
    `claim_email_2` VARCHAR(255) NULL,
    `claim_email_3` VARCHAR(255) NULL,
    `claim_email_4` VARCHAR(255) NULL,
    `claim_email_5` VARCHAR(255) NULL,
    `period` INT(2) NOT NULL DEFAULT 1,
    `status` VARCHAR(50) NOT NULL DEFAULT 'Pending',
    `code` INT(11) NULL,
    `message` TEXT NULL,
    `errors` TEXT NULL,
    `expire_date` DATETIME NULL,
    `auth_info` VARCHAR(255) NULL,
    `application_id` VARCHAR(100) NULL,
    `registration_number` VARCHAR(100) NULL,
    `application_date` DATE NULL,
    `registration_date` DATE NULL,
    `jurisdiction` VARCHAR(50) NULL,
    `owner_name` VARCHAR(255) NULL,
    `owner_email` VARCHAR(255) NULL,
    `owner_company` VARCHAR(255) NULL,
    `owner_address1` VARCHAR(255) NULL,
    `owner_address2` VARCHAR(255) NULL,
    `owner_city` VARCHAR(100) NULL,
    `owner_state` VARCHAR(100) NULL,
    `owner_postcode` VARCHAR(50) NULL,
    `owner_country` VARCHAR(10) NULL,
    `owner_phone` VARCHAR(50) NULL,
    `documents_uploaded` TINYINT(1) NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_service_id` (`whmcs_service_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_status` (`status`),
    KEY `idx_mark_id` (`mark_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Document uploads tracking
CREATE TABLE IF NOT EXISTS `mod_ascio_tmch_documents` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `tmch_id` INT(11) NOT NULL,
    `doc_type` VARCHAR(50) NOT NULL COMMENT 'TrademarkCopy, ProofOfUse, Declaration, etc.',
    `filename` VARCHAR(255) NOT NULL,
    `uploaded_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `status` VARCHAR(50) NOT NULL DEFAULT 'Pending' COMMENT 'Pending, Submitted, Accepted, Rejected',
    `message` TEXT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_tmch_id` (`tmch_id`),
    CONSTRAINT `fk_tmch_documents` FOREIGN KEY (`tmch_id`) REFERENCES `mod_ascio_tmch` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
