-- Ascio Defensive Registration (DPML) module database schema

CREATE TABLE IF NOT EXISTS `mod_ascio_defensive` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `order_id` VARCHAR(50) NOT NULL,
    `whmcs_service_id` INT(11) NOT NULL,
    `user_id` INT(11) NOT NULL,
    `handle` VARCHAR(50) NULL,
    `name` VARCHAR(255) NOT NULL COMMENT 'Defensive domain name',
    `mark_handle` VARCHAR(50) NULL COMMENT 'Associated TMCH mark handle',
    `auth_info` VARCHAR(255) NULL COMMENT 'Authorization code',
    `encoding` VARCHAR(50) NULL,
    `period` INT(2) NOT NULL DEFAULT 1 COMMENT 'Registration period in years',
    `status` VARCHAR(50) NOT NULL DEFAULT 'Pending',
    `code` INT(11) NULL COMMENT 'API result code',
    `message` TEXT NULL COMMENT 'API result message or error',
    `errors` TEXT NULL COMMENT 'JSON encoded error details',
    `expire_date` DATETIME NULL,
    `owner_name` VARCHAR(255) NULL,
    `owner_email` VARCHAR(255) NULL,
    `owner_company` VARCHAR(255) NULL,
    `owner_address1` VARCHAR(255) NULL,
    `owner_address2` VARCHAR(255) NULL,
    `owner_city` VARCHAR(100) NULL,
    `owner_state` VARCHAR(100) NULL,
    `owner_postcode` VARCHAR(50) NULL,
    `owner_country` VARCHAR(10) NULL,
    `owner_phone` VARCHAR(50) NULL,
    `admin_name` VARCHAR(255) NULL,
    `admin_email` VARCHAR(255) NULL,
    `admin_company` VARCHAR(255) NULL,
    `admin_phone` VARCHAR(50) NULL,
    `tech_name` VARCHAR(255) NULL,
    `tech_email` VARCHAR(255) NULL,
    `tech_company` VARCHAR(255) NULL,
    `tech_phone` VARCHAR(50) NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_service_id` (`whmcs_service_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_status` (`status`),
    KEY `idx_mark_handle` (`mark_handle`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
