<?php


 function autoload_ca5124cc493862de39cebdb26d543f92($class)
{
    $classes = array(
        'ascio\v3\AscioService' => __DIR__ .'/AscioService.php',
        'ascio\v3\CreateOrder' => __DIR__ .'/CreateOrder.php',
        'ascio\v3\CreateOrderResponse' => __DIR__ .'/CreateOrderResponse.php',
        'ascio\v3\ValidateOrder' => __DIR__ .'/ValidateOrder.php',
        'ascio\v3\ValidateOrderResponse' => __DIR__ .'/ValidateOrderResponse.php',
        'ascio\v3\GetOrder' => __DIR__ .'/GetOrder.php',
        'ascio\v3\GetOrderResponse' => __DIR__ .'/GetOrderResponse.php',
        'ascio\v3\GetOrders' => __DIR__ .'/GetOrders.php',
        'ascio\v3\GetOrdersResponse' => __DIR__ .'/GetOrdersResponse.php',
        'ascio\v3\GetMark' => __DIR__ .'/GetMark.php',
        'ascio\v3\GetMarkResponse' => __DIR__ .'/GetMarkResponse.php',
        'ascio\v3\GetDefensive' => __DIR__ .'/GetDefensive.php',
        'ascio\v3\GetDefensiveResponse' => __DIR__ .'/GetDefensiveResponse.php',
        'ascio\v3\GetNameWatch' => __DIR__ .'/GetNameWatch.php',
        'ascio\v3\GetNameWatchResponse' => __DIR__ .'/GetNameWatchResponse.php',
        'ascio\v3\GetSslCertificate' => __DIR__ .'/GetSslCertificate.php',
        'ascio\v3\GetSslCertificateResponse' => __DIR__ .'/GetSslCertificateResponse.php',
        'ascio\v3\GetAutoInstallSsl' => __DIR__ .'/GetAutoInstallSsl.php',
        'ascio\v3\GetAutoInstallSslResponse' => __DIR__ .'/GetAutoInstallSslResponse.php',
        'ascio\v3\GetMessages' => __DIR__ .'/GetMessages.php',
        'ascio\v3\GetMessagesResponse' => __DIR__ .'/GetMessagesResponse.php',
        'ascio\v3\PollQueue' => __DIR__ .'/PollQueue.php',
        'ascio\v3\PollQueueResponse' => __DIR__ .'/PollQueueResponse.php',
        'ascio\v3\AckQueueMessage' => __DIR__ .'/AckQueueMessage.php',
        'ascio\v3\AckQueueMessageResponse' => __DIR__ .'/AckQueueMessageResponse.php',
        'ascio\v3\GetQueueMessage' => __DIR__ .'/GetQueueMessage.php',
        'ascio\v3\GetQueueMessageResponse' => __DIR__ .'/GetQueueMessageResponse.php',
        'ascio\v3\UploadDocumentation' => __DIR__ .'/UploadDocumentation.php',
        'ascio\v3\UploadDocumentationResponse' => __DIR__ .'/UploadDocumentationResponse.php',
        'ascio\v3\UploadMessage' => __DIR__ .'/UploadMessage.php',
        'ascio\v3\UploadMessageResponse' => __DIR__ .'/UploadMessageResponse.php',
        'ascio\v3\AbstractOrderRequest' => __DIR__ .'/AbstractOrderRequest.php',
        'ascio\v3\OrderType' => __DIR__ .'/OrderType.php',
        'ascio\v3\MarkOrderRequest' => __DIR__ .'/MarkOrderRequest.php',
        'ascio\v3\AbstractMark' => __DIR__ .'/AbstractMark.php',
        'ascio\v3\MarkServiceType' => __DIR__ .'/MarkServiceType.php',
        'ascio\v3\NotificationFrequencyType' => __DIR__ .'/NotificationFrequencyType.php',
        'ascio\v3\Registrant' => __DIR__ .'/Registrant.php',
        'ascio\v3\Contact' => __DIR__ .'/Contact.php',
        'ascio\v3\Extensions' => __DIR__ .'/Extensions.php',
        'ascio\v3\KeyValue' => __DIR__ .'/KeyValue.php',
        'ascio\v3\AutoInstallSslOrderRequest' => __DIR__ .'/AutoInstallSslOrderRequest.php',
        'ascio\v3\AutoInstallSsl' => __DIR__ .'/AutoInstallSsl.php',
        'ascio\v3\SslCertificateOrderRequest' => __DIR__ .'/SslCertificateOrderRequest.php',
        'ascio\v3\SslCertificate' => __DIR__ .'/SslCertificate.php',
        'ascio\v3\WebServerType' => __DIR__ .'/WebServerType.php',
        'ascio\v3\SslDomainValidationType' => __DIR__ .'/SslDomainValidationType.php',
        'ascio\v3\TreatyOrStatuteMark' => __DIR__ .'/TreatyOrStatuteMark.php',
        'ascio\v3\Trademark' => __DIR__ .'/Trademark.php',
        'ascio\v3\CourtValidatedMark' => __DIR__ .'/CourtValidatedMark.php',
        'ascio\v3\SecurityHeaderDetails' => __DIR__ .'/SecurityHeaderDetails.php',
        'ascio\v3\ArrayOfMarkOrderDocument' => __DIR__ .'/ArrayOfMarkOrderDocument.php',
        'ascio\v3\MarkOrderDocument' => __DIR__ .'/MarkOrderDocument.php',
        'ascio\v3\Attachment' => __DIR__ .'/Attachment.php',
        'ascio\v3\MarkOrderDocType' => __DIR__ .'/MarkOrderDocType.php',
        'ascio\v3\NameWatchOrderRequest' => __DIR__ .'/NameWatchOrderRequest.php',
        'ascio\v3\NameWatch' => __DIR__ .'/NameWatch.php',
        'ascio\v3\DefensiveOrderRequest' => __DIR__ .'/DefensiveOrderRequest.php',
        'ascio\v3\Defensive' => __DIR__ .'/Defensive.php',
        'ascio\v3\AbstractResponse' => __DIR__ .'/AbstractResponse.php',
        'ascio\v3\OrderInfo' => __DIR__ .'/OrderInfo.php',
        'ascio\v3\OrderStatusType' => __DIR__ .'/OrderStatusType.php',
        'ascio\v3\GetOrderRequest' => __DIR__ .'/GetOrderRequest.php',
        'ascio\v3\GetOrdersRequest' => __DIR__ .'/GetOrdersRequest.php',
        'ascio\v3\ArrayOfOrderStatusType' => __DIR__ .'/ArrayOfOrderStatusType.php',
        'ascio\v3\ArrayOfOrderType' => __DIR__ .'/ArrayOfOrderType.php',
        'ascio\v3\ArrayOfObjectType' => __DIR__ .'/ArrayOfObjectType.php',
        'ascio\v3\ObjectType' => __DIR__ .'/ObjectType.php',
        'ascio\v3\SearchOrderSortType' => __DIR__ .'/SearchOrderSortType.php',
        'ascio\v3\PagingInfo' => __DIR__ .'/PagingInfo.php',
        'ascio\v3\ArrayOfOrderInfo' => __DIR__ .'/ArrayOfOrderInfo.php',
        'ascio\v3\GetMarkRequest' => __DIR__ .'/GetMarkRequest.php',
        'ascio\v3\MarkInfo' => __DIR__ .'/MarkInfo.php',
        'ascio\v3\GetDefensiveRequest' => __DIR__ .'/GetDefensiveRequest.php',
        'ascio\v3\DefensiveInfo' => __DIR__ .'/DefensiveInfo.php',
        'ascio\v3\GetNameWatchRequest' => __DIR__ .'/GetNameWatchRequest.php',
        'ascio\v3\NameWatchInfo' => __DIR__ .'/NameWatchInfo.php',
        'ascio\v3\GetSslCertificateRequest' => __DIR__ .'/GetSslCertificateRequest.php',
        'ascio\v3\SslCertificateInfo' => __DIR__ .'/SslCertificateInfo.php',
        'ascio\v3\GetAutoInstallSslRequest' => __DIR__ .'/GetAutoInstallSslRequest.php',
        'ascio\v3\AutoInstallSslInfo' => __DIR__ .'/AutoInstallSslInfo.php',
        'ascio\v3\GetMessagesRequest' => __DIR__ .'/GetMessagesRequest.php',
        'ascio\v3\ArrayOfMessage' => __DIR__ .'/ArrayOfMessage.php',
        'ascio\v3\Message' => __DIR__ .'/Message.php',
        'ascio\v3\ArrayOfAttachment' => __DIR__ .'/ArrayOfAttachment.php',
        'ascio\v3\MessageType' => __DIR__ .'/MessageType.php',
        'ascio\v3\PollQueueRequest' => __DIR__ .'/PollQueueRequest.php',
        'ascio\v3\QueueMessage' => __DIR__ .'/QueueMessage.php',
        'ascio\v3\ArrayOfErrorCode' => __DIR__ .'/ArrayOfErrorCode.php',
        'ascio\v3\ErrorCode' => __DIR__ .'/ErrorCode.php',
        'ascio\v3\AckQueueMessageRequest' => __DIR__ .'/AckQueueMessageRequest.php',
        'ascio\v3\GetQueueMessageRequest' => __DIR__ .'/GetQueueMessageRequest.php',
        'ascio\v3\UploadDocumentationRequest' => __DIR__ .'/UploadDocumentationRequest.php',
        'ascio\v3\UploadMessageRequest' => __DIR__ .'/UploadMessageRequest.php',
        'ascio\v3\ArrayOfstring' => __DIR__ .'/ArrayOfstring.php',
        'ascio\v3\ArrayOfint' => __DIR__ .'/ArrayOfint.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_ca5124cc493862de39cebdb26d543f92');

// Do nothing. The rest is just leftovers from the code generation.
{
}
