<?php
/**
 * Ascio WHMCS Registrar Module - Transfer Tracker
 *
 * Tracks domain transfer progress through various stages.
 * Provides status information for display in WHMCS admin panel.
 */

namespace ascio;

use Illuminate\Database\Capsule\Manager as Capsule;

/**
 * Transfer Tracker class for monitoring domain transfer progress
 */
class TransferTracker
{
    /** @var string Table name for transfer status storage */
    const TABLE_NAME = 'tblascio_transfer_status';

    /** @var array Transfer stages in order */
    const STAGES = [
        'pending',
        'validating',
        'processing',
        'completed',
        'failed'
    ];

    /**
     * Get the transfer status for a domain
     *
     * @param int $domainId WHMCS domain ID
     * @return array|null Transfer status data or null if not found
     */
    public static function getTransferStatus(int $domainId): ?array
    {
        self::ensureTable();

        $status = Capsule::table(self::TABLE_NAME)
            ->where('domain_id', $domainId)
            ->first();

        if (!$status) {
            return null;
        }

        return [
            'id' => $status->id ?? 0, // Auto-generated by DB
            'domain_id' => $status->domain_id,
            'domain_name' => $status->domain_name,
            'current_stage' => $status->current_stage,
            'order_id' => $status->order_id,
            'started_at' => $status->started_at,
            'updated_at' => $status->updated_at,
            'message' => $status->message,
        ];
    }

    /**
     * Update or create transfer status for a domain
     *
     * @param int $domainId WHMCS domain ID
     * @param string $stage Current transfer stage
     * @param string|null $orderId Ascio order ID (optional)
     * @param string|null $message Status message (optional)
     * @return bool Success
     */
    public static function updateStatus(int $domainId, string $stage, ?string $orderId = null, ?string $message = null): bool
    {
        self::ensureTable();

        // Validate stage
        if (!in_array($stage, self::STAGES)) {
            logActivity("TransferTracker: Invalid stage '$stage' for domain $domainId");
            return false;
        }

        // Get domain name from WHMCS
        $domain = Capsule::table('tbldomains')
            ->where('id', $domainId)
            ->first();

        $domainName = $domain->domain ?? '';

        $existingStatus = Capsule::table(self::TABLE_NAME)
            ->where('domain_id', $domainId)
            ->first();

        $now = date('Y-m-d H:i:s');

        if ($existingStatus) {
            // Update existing record
            $updateData = [
                'current_stage' => $stage,
                'updated_at' => $now,
            ];

            if ($orderId !== null) {
                $updateData['order_id'] = $orderId;
            }

            if ($message !== null) {
                $updateData['message'] = $message;
            }

            Capsule::table(self::TABLE_NAME)
                ->where('domain_id', $domainId)
                ->update($updateData);
        } else {
            // Create new record
            Capsule::table(self::TABLE_NAME)->insert([
                'domain_id' => $domainId,
                'domain_name' => $domainName,
                'current_stage' => $stage,
                'order_id' => $orderId,
                'started_at' => $now,
                'updated_at' => $now,
                'message' => $message,
            ]);
        }

        logActivity("TransferTracker: Updated domain $domainId ($domainName) to stage '$stage'");
        return true;
    }

    /**
     * Get all available transfer stages
     *
     * @return array List of stage names
     */
    public static function getStages(): array
    {
        return self::STAGES;
    }

    /**
     * Ensure the transfer status table exists
     *
     * @return void
     */
    public static function ensureTable(): void
    {
        if (!Capsule::schema()->hasTable(self::TABLE_NAME)) {
            Capsule::schema()->create(self::TABLE_NAME, function ($table) {
                $table->increments('id');
                $table->integer('domain_id')->unsigned();
                $table->string('domain_name', 255);
                $table->string('current_stage', 50);
                $table->string('order_id', 255)->nullable();
                $table->timestamp('started_at')->nullable();
                $table->timestamp('updated_at')->nullable();
                $table->text('message')->nullable();
                $table->unique('domain_id');
                $table->index('current_stage');
            });
        }
    }

    /**
     * Delete transfer status for a domain (cleanup after transfer completes/fails)
     *
     * @param int $domainId WHMCS domain ID
     * @return bool Success
     */
    public static function deleteStatus(int $domainId): bool
    {
        self::ensureTable();

        $deleted = Capsule::table(self::TABLE_NAME)
            ->where('domain_id', $domainId)
            ->delete();

        return $deleted > 0;
    }

    /**
     * Get human-readable label for a stage
     *
     * @param string $stage Stage name
     * @return string Human-readable label
     */
    public static function getStageLabel(string $stage): string
    {
        $labels = [
            'pending' => 'Pending',
            'validating' => 'Validating',
            'processing' => 'Processing',
            'completed' => 'Completed',
            'failed' => 'Failed',
        ];

        return $labels[$stage] ?? ucfirst($stage);
    }

    /**
     * Get the stage index (0-based) for progress calculation
     *
     * @param string $stage Stage name
     * @return int Stage index or -1 if not found
     */
    public static function getStageIndex(string $stage): int
    {
        $index = array_search($stage, self::STAGES);
        return $index !== false ? $index : -1;
    }

    /**
     * Calculate progress percentage (0-100)
     *
     * @param string $stage Current stage
     * @return int Progress percentage
     */
    public static function getProgressPercentage(string $stage): int
    {
        $index = self::getStageIndex($stage);

        if ($index < 0) {
            return 0;
        }

        // completed and failed are both 100%
        if ($stage === 'completed' || $stage === 'failed') {
            return 100;
        }

        // For stages 0-2 (pending, validating, processing)
        // Map to percentages: 0=25%, 1=50%, 2=75%
        return ($index + 1) * 25;
    }

    /**
     * Map Ascio order status to transfer stage
     *
     * @param string $orderStatus Ascio order status
     * @return string Transfer stage
     */
    public static function mapOrderStatusToStage(string $orderStatus): string
    {
        $statusMap = [
            'NotSet' => 'pending',
            'Pending' => 'validating',
            'Pending_End_User_Action' => 'validating',
            'Pending_Documentation' => 'validating',
            'Pending_Approval' => 'validating',
            'Pending_Registry' => 'processing',
            'Processing' => 'processing',
            'Completed' => 'completed',
            'Successful' => 'completed',
            'Failed' => 'failed',
            'Invalid' => 'failed',
            'Cancelled' => 'failed',
        ];

        return $statusMap[$orderStatus] ?? 'pending';
    }

    /**
     * Generate HTML for the transfer progress display
     *
     * @param array $status Transfer status data
     * @return string HTML output
     */
    public static function renderProgressHtml(array $status): string
    {
        $currentStage = $status['current_stage'];
        $currentIndex = self::getStageIndex($currentStage);
        $percentage = self::getProgressPercentage($currentStage);

        $isFailed = $currentStage === 'failed';
        $isCompleted = $currentStage === 'completed';

        $barColor = $isFailed ? '#d9534f' : ($isCompleted ? '#5cb85c' : '#337ab7');

        $html = '<div class="ascio-transfer-progress" style="margin: 15px 0; padding: 15px; background: #f9f9f9; border: 1px solid #ddd; border-radius: 4px;">';
        $html .= '<h4 style="margin-top: 0; margin-bottom: 15px;">Transfer Progress</h4>';

        // Progress bar
        $html .= '<div style="background: #e9ecef; border-radius: 4px; height: 20px; overflow: hidden; margin-bottom: 15px;">';
        $html .= '<div style="background: ' . $barColor . '; height: 100%; width: ' . $percentage . '%; transition: width 0.3s ease;"></div>';
        $html .= '</div>';

        // Stage indicators
        $html .= '<div style="display: flex; justify-content: space-between; margin-bottom: 15px;">';

        $displayStages = ['pending', 'validating', 'processing', 'completed'];
        foreach ($displayStages as $index => $stage) {
            $label = self::getStageLabel($stage);
            $isActive = $stage === $currentStage;
            $isPassed = self::getStageIndex($stage) < $currentIndex;

            if ($isFailed && $stage === $currentStage) {
                $color = '#d9534f';
                $label = 'Failed';
            } elseif ($isActive) {
                $color = '#337ab7';
            } elseif ($isPassed) {
                $color = '#5cb85c';
            } else {
                $color = '#999';
            }

            $fontWeight = $isActive ? 'bold' : 'normal';

            $html .= '<div style="text-align: center; flex: 1;">';
            $html .= '<div style="width: 24px; height: 24px; border-radius: 50%; background: ' . $color . '; color: white; margin: 0 auto 5px; line-height: 24px; font-size: 12px;">';
            $html .= ($isPassed || ($isActive && ($isCompleted || $isFailed))) ? '&#10003;' : ($index + 1);
            $html .= '</div>';
            $html .= '<div style="font-size: 12px; color: ' . $color . '; font-weight: ' . $fontWeight . ';">' . htmlspecialchars($label) . '</div>';
            $html .= '</div>';
        }

        $html .= '</div>';

        // Status details
        $html .= '<div style="font-size: 13px; color: #666;">';
        $html .= '<strong>Order ID:</strong> ' . htmlspecialchars($status['order_id'] ?? 'N/A') . '<br>';
        $html .= '<strong>Started:</strong> ' . htmlspecialchars($status['started_at'] ?? 'N/A') . '<br>';
        $html .= '<strong>Last Updated:</strong> ' . htmlspecialchars($status['updated_at'] ?? 'N/A');

        if (!empty($status['message'])) {
            $messageColor = $isFailed ? '#d9534f' : '#666';
            $html .= '<br><strong>Message:</strong> <span style="color: ' . $messageColor . ';">' . htmlspecialchars($status['message']) . '</span>';
        }

        $html .= '</div>';
        $html .= '</div>';

        return $html;
    }
}
