<?php

namespace Ascio\Tests\Unit;

use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\Attributes\Test;
use ascio\FieldRegistry;
use ascio\ConditionalFieldMapper;
use ascio\FieldGenerator;

/**
 * Unit tests for FieldGenerator
 *
 * Verifies that given known API data + registry, generated PHP/JS output
 * matches the expected format.
 */
class FieldGeneratorTest extends TestCase
{
    private FieldGenerator $generator;
    private FieldRegistry $registry;

    protected function setUp(): void
    {
        parent::setUp();
        $this->registry = new FieldRegistry();
        $mapper = new ConditionalFieldMapper($this->registry);
        $this->generator = new FieldGenerator($this->registry, $mapper);
    }

    // ========================================================================
    // PHP Generation Tests
    // ========================================================================

    #[Test]
    public function generatedPhpStartsWithPhpTag(): void
    {
        $apiData = $this->makeApiData(['.it' => ['Registrant.Type']]);
        $output = $this->generator->generateAdditionalFields($apiData);

        $this->assertStringStartsWith('<?php', $output);
    }

    #[Test]
    public function generatedPhpContainsAutoGeneratedHeader(): void
    {
        $apiData = $this->makeApiData(['.it' => ['Registrant.Type']]);
        $output = $this->generator->generateAdditionalFields($apiData);

        $this->assertStringContainsString('AUTO-GENERATED', $output);
        $this->assertStringContainsString('FieldRegistry.php', $output);
    }

    #[Test]
    public function generatedPhpContainsFieldDefinitions(): void
    {
        $apiData = $this->makeApiData(['.it' => ['Registrant.Type', 'Registrant.OrganisationNumber']]);
        $output = $this->generator->generateAdditionalFields($apiData);

        $this->assertStringContainsString('$additionaldomainfields[".it"]', $output);
        $this->assertStringContainsString('"Name" => \'Legal Type\'', $output);
        $this->assertStringContainsString('"Name" => \'Tax ID\'', $output);
    }

    #[Test]
    public function generatedPhpContainsRemoveDirectives(): void
    {
        $apiData = $this->makeApiData(['.ca' => ['Registrant.Type']]);
        $output = $this->generator->generateAdditionalFields($apiData);

        $this->assertStringContainsString('"Remove" => true', $output);
        $this->assertStringContainsString('Legal Type', $output);
        $this->assertStringContainsString('CIRA Agreement', $output);
        $this->assertStringContainsString('WHOIS Opt-out', $output);
    }

    #[Test]
    public function generatedPhpContainsVariantCopies(): void
    {
        $apiData = $this->makeApiData(['.fr' => ['Registrant.Type']]);
        $output = $this->generator->generateAdditionalFields($apiData);

        $this->assertStringContainsString('$additionaldomainfields[".re"] = $additionaldomainfields[".fr"]', $output);
        $this->assertStringContainsString('$additionaldomainfields[".pm"] = $additionaldomainfields[".fr"]', $output);
    }

    #[Test]
    public function generatedPhpContainsConditionalRules(): void
    {
        $apiData = $this->makeApiDataWithConditionals(
            '.it',
            ['Registrant.Type', 'Registrant.BirthCountry'],
            [
                [
                    'field' => 'Registrant.Type',
                    'conditions' => [
                        ['context' => 'individual', 'fields' => ['Registrant.BirthCountry']],
                    ],
                ],
            ]
        );
        $output = $this->generator->generateAdditionalFields($apiData);

        $this->assertStringContainsString('ascio_conditional_fields', $output);
        $this->assertStringContainsString("'Birth Country'", $output);
        $this->assertStringContainsString("'depends_on'", $output);
        $this->assertStringContainsString("'Legal Type'", $output);
    }

    #[Test]
    public function generatedPhpIsValidSyntax(): void
    {
        $apiData = $this->makeApiData([
            '.it' => ['Registrant.Type', 'Registrant.OrganisationNumber', 'Registrant.BirthCountry'],
            '.ca' => ['Registrant.Type', 'CIRA.Agreement'],
            '.fr' => ['Registrant.Type'],
        ]);
        $output = $this->generator->generateAdditionalFields($apiData);

        // Write to temp file and check syntax
        $tmpFile = tempnam(sys_get_temp_dir(), 'ascio_test_');
        file_put_contents($tmpFile, $output);

        $result = exec("php -l {$tmpFile} 2>&1", $outputLines, $returnCode);
        unlink($tmpFile);

        $this->assertEquals(0, $returnCode, "Generated PHP has syntax errors: " . implode("\n", $outputLines));
    }

    #[Test]
    public function generatedPhpDoesNotContainVariantTldDirectly(): void
    {
        // Variant TLDs should only appear as copies, not with their own field definitions
        $apiData = $this->makeApiData(['.ru' => ['Registrant.Type']]);
        // Also include .su in the API data - it should be skipped since it's a variant
        $apiData[] = [
            'tld' => '.su',
            'required_fields' => ['Registrant.Type'],
            'conditional_fields' => [],
        ];
        $output = $this->generator->generateAdditionalFields($apiData);

        // .su should appear only as a copy, not as a direct definition section
        $this->assertStringNotContainsString('$additionaldomainfields[".su"][] = array(', $output);
        $this->assertStringContainsString('$additionaldomainfields[".su"] = $additionaldomainfields[".ru"]', $output);
    }

    // ========================================================================
    // JS Generation Tests
    // ========================================================================

    #[Test]
    public function generatedJsContainsIife(): void
    {
        $apiData = $this->makeApiData(['.it' => ['Registrant.Type']]);
        $output = $this->generator->generateConditionalJs($apiData);

        $this->assertStringContainsString('(function()', $output);
        $this->assertStringContainsString('})();', $output);
    }

    #[Test]
    public function generatedJsContainsAutoGeneratedHeader(): void
    {
        $apiData = $this->makeApiData(['.it' => ['Registrant.Type']]);
        $output = $this->generator->generateConditionalJs($apiData);

        $this->assertStringContainsString('AUTO-GENERATED', $output);
    }

    #[Test]
    public function generatedJsContainsConditionalRules(): void
    {
        $apiData = $this->makeApiDataWithConditionals(
            '.it',
            ['Registrant.Type', 'Registrant.BirthCountry'],
            [
                [
                    'field' => 'Registrant.Type',
                    'conditions' => [
                        ['context' => 'individual', 'fields' => ['Registrant.BirthCountry']],
                    ],
                ],
            ]
        );
        $output = $this->generator->generateConditionalJs($apiData);

        $this->assertStringContainsString('conditionalRules', $output);
        $this->assertStringContainsString('dependsOn', $output);
        $this->assertStringContainsString('showWhen', $output);
    }

    #[Test]
    public function generatedJsContainsVariantRules(): void
    {
        $apiData = $this->makeApiDataWithConditionals(
            '.fr',
            ['Registrant.Type', 'Registrant.BirthDate'],
            [
                [
                    'field' => 'Registrant.Type',
                    'conditions' => [
                        ['context' => 'individual', 'fields' => ['Registrant.BirthDate']],
                    ],
                ],
            ]
        );
        $output = $this->generator->generateConditionalJs($apiData);

        // Variants should be expanded in JS
        $this->assertStringContainsString('.re', $output);
        $this->assertStringContainsString('.pm', $output);
    }

    #[Test]
    public function generatedJsExposesAscioFieldsDebugApi(): void
    {
        $apiData = $this->makeApiData(['.it' => ['Registrant.Type']]);
        $output = $this->generator->generateConditionalJs($apiData);

        $this->assertStringContainsString('window.AscioFields', $output);
        $this->assertStringContainsString('getCurrentTld', $output);
        $this->assertStringContainsString('applyConditionalRules', $output);
    }

    // ========================================================================
    // JSON Generation Tests
    // ========================================================================

    #[Test]
    public function generatedJsonIsValid(): void
    {
        $apiData = $this->makeApiDataWithConditionals(
            '.it',
            ['Registrant.Type', 'Registrant.BirthCountry'],
            [
                [
                    'field' => 'Registrant.Type',
                    'conditions' => [
                        ['context' => 'individual', 'fields' => ['Registrant.BirthCountry']],
                    ],
                ],
            ]
        );
        $output = $this->generator->generateConditionalJson($apiData);

        $decoded = json_decode($output, true);
        $this->assertNotNull($decoded, "Generated JSON is not valid: " . json_last_error_msg());
    }

    #[Test]
    public function generatedJsonContainsExpectedStructure(): void
    {
        $apiData = $this->makeApiDataWithConditionals(
            '.it',
            ['Registrant.Type', 'Registrant.BirthCountry'],
            [
                [
                    'field' => 'Registrant.Type',
                    'conditions' => [
                        ['context' => 'individual', 'fields' => ['Registrant.BirthCountry']],
                    ],
                ],
            ]
        );
        $output = $this->generator->generateConditionalJson($apiData);
        $decoded = json_decode($output, true);

        $this->assertArrayHasKey('.it', $decoded);
        $this->assertArrayHasKey('Birth Country', $decoded['.it']);
        $this->assertEquals('Legal Type', $decoded['.it']['Birth Country']['depends_on']);
    }

    // ========================================================================
    // Empty/Edge Case Tests
    // ========================================================================

    #[Test]
    public function emptyApiDataGeneratesMinimalPhp(): void
    {
        $output = $this->generator->generateAdditionalFields([]);
        $this->assertStringStartsWith('<?php', $output);
        $this->assertStringContainsString('AUTO-GENERATED', $output);
    }

    #[Test]
    public function tldWithNoRecognizedFieldsIsSkipped(): void
    {
        $apiData = [
            [
                'tld' => '.unknown',
                'required_fields' => ['Completely.Unknown.Field'],
                'conditional_fields' => [],
            ],
        ];
        $output = $this->generator->generateAdditionalFields($apiData);

        $this->assertStringNotContainsString('.unknown', $output);
    }

    #[Test]
    public function tldNormalizationHandsMissingDot(): void
    {
        $apiData = [
            [
                'tld' => 'it', // No dot prefix
                'required_fields' => ['Registrant.Type'],
                'conditional_fields' => [],
            ],
        ];
        $output = $this->generator->generateAdditionalFields($apiData);

        $this->assertStringContainsString('$additionaldomainfields[".it"]', $output);
    }

    // ========================================================================
    // Helpers
    // ========================================================================

    private function makeApiData(array $tldFields): array
    {
        $data = [];
        foreach ($tldFields as $tld => $fields) {
            $data[] = [
                'tld' => $tld,
                'required_fields' => $fields,
                'conditional_fields' => [],
            ];
        }
        return $data;
    }

    private function makeApiDataWithConditionals(string $tld, array $requiredFields, array $conditionalFields): array
    {
        return [
            [
                'tld' => $tld,
                'required_fields' => $requiredFields,
                'conditional_fields' => $conditionalFields,
            ],
        ];
    }
}
